### ISSUE TITLE
Will not compile on Windows 10

### ISSUE THREAD

**Issue by caecos** [liquidcitymotors/Via-for-VCVRack#12]

**Comment by caecos** [comment]
$ make
g++  -Wsuggest-override -std=c++11 -DBUILD_VIRTUAL -I./Via/modules/inc -I./Via/synthesis/inc -I./Via/io/inc -I./Via/ui/inc  -DSLUG=Starling_Via_Meta -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Via_Meta.cpp.o src/Via_Meta.cpp
src/Via_Meta.cpp:1:10: fatal error: meta.hpp: No such file or directory
 #include "meta.hpp"
          ^~~~~~~~~~
compilation terminated.

**Comment by caecos** [comment]
$ make
g++  -Wsuggest-override -std=c++11 -DBUILD_VIRTUAL -I./Via/modules/inc -I./Via/synthesis/inc -I./Via/io/inc -I./Via/ui/inc  -DSLUG=Starling_Via_Meta -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Via_Meta.cpp.o src/Via_Meta.cpp
src/Via_Meta.cpp:1:10: fatal error: meta.hpp: No such file or directory
 #include "meta.hpp"
          ^~~~~~~~~~
compilation terminated.

**Comment by liquidcitymotors** [comment]
Hi! Did you clone the submodules? This is a pre-release version so the readme doesn't mention the need to do that, my apologies. In a similar fashion to the Fundamental plugins, you need to run 

`git submodule update --init --recursive`

**Comment by caecos** [comment]
Yes...and still this error:
make: *** [../../compile.mk:65: build/src/Via_Scanner.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
This is what I get:

g++  -Wsuggest-override -std=c++11 -DBUILD_VIRTUAL -I./Via/modules/inc -I./Via/synthesis/inc -I./Via/io/inc -I./Via/ui/inc  -DSLUG=Starling_Via -fPIC -I../../include -I../../dep/include -DVERSION=0.9.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Via_Meta.cpp.o src/Via_Meta.cpp
In file included from ./Via/io/inc/via_virtual_module.hpp:14,
                 from ./Via/io/inc/via_platform_binding.hpp:18,
                 from ./Via/ui/inc/user_interface.hpp:13,
                 from ./Via/modules/inc/meta.hpp:11,
                 from src/Via_Meta.cpp:1:
./Via/synthesis/inc/dsp.hpp: In function 'int32_t __SSAT(int32_t, int32_t)':
./Via/synthesis/inc/dsp.hpp:573:25: warning: left shift of negative value [-Wshift-negative-value]
  } else if (X < ((-1 << Y) + 1)) {
                         ^
./Via/synthesis/inc/dsp.hpp:574:18: warning: left shift of negative value [-Wshift-negative-value]
   return ((-1 << Y) + 1);
                  ^
g++  -Wsuggest-override -std=c++11 -DBUILD_VIRTUAL -I./Via/modules/inc -I./Via/synthesis/inc -I./Via/io/inc -I./Via/ui/inc  -DSLUG=Starling_Via -fPIC -I../../include -I../../dep/include -DVERSION=0.9.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Via_Scanner.cpp.o src/Via_Scanner.cpp
In file included from ./Via/io/inc/via_virtual_module.hpp:14,
                 from ./Via/io/inc/via_platform_binding.hpp:18,
                 from ./Via/ui/inc/user_interface.hpp:13,
                 from ./Via/modules/inc/scanner.hpp:17,
                 from src/Via_Scanner.cpp:1:
./Via/synthesis/inc/dsp.hpp: In function 'int32_t __SSAT(int32_t, int32_t)':
./Via/synthesis/inc/dsp.hpp:573:25: warning: left shift of negative value [-Wshift-negative-value]
  } else if (X < ((-1 << Y) + 1)) {
                         ^
./Via/synthesis/inc/dsp.hpp:574:18: warning: left shift of negative value [-Wshift-negative-value]
   return ((-1 << Y) + 1);
                  ^
In file included from ./Via/io/inc/via_virtual_module.hpp:14,
                 from ./Via/io/inc/via_platform_binding.hpp:18,
                 from ./Via/ui/inc/user_interface.hpp:13,
                 from ./Via/modules/inc/scanner.hpp:17,
                 from src/Via_Scanner.cpp:1:
./Via/synthesis/inc/dsp.hpp: At global scope:
./Via/synthesis/inc/dsp.hpp:807:23: error: conflicting declaration of C function 'int32_t getSampleQuinticSplineDeltaValue(uint32_t, uint32_t, uint32_t*, int32_t*, uint32_t)'
 static inline int32_t getSampleQuinticSplineDeltaValue(uint32_t phase, uint32_t morph,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./Via/synthesis/inc/dsp.hpp:743:23: note: previous declaration 'int32_t getSampleQuinticSplineDeltaValue(uint32_t, uint32_t, uint32_t*, int32_t*)'
 static inline int32_t getSampleQuinticSplineDeltaValue(uint32_t phase, uint32_t morph,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [../../compile.mk:65: build/src/Via_Scanner.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
I got it to compile by commenting out lines 743-805 of Via-for-VCVRack\Via\synthesis\inc\dsp.hpp

**Comment by SteveRussell33** [comment]
Starling_Via-0.9.0-win.zip

https://drive.google.com/open?id=1jlYA1BqRk4lWZJi1vTA0CXyZU3r_Ubo3

**Comment by caecos** [comment]
Thx, I will try it tonight after works... regards...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : SteveRussell33 <notifications@github.com>
Envoyé : lundi, janvier 14, 2019 12:42
À : liquidcitymotors/Via-for-VCVRack
Cc : caecos; Mention
Objet : Re: [liquidcitymotors/Via-for-VCVRack] Will not compile on Windows 10 (#12)


Starling_Via-0.9.0-win.zip

https://drive.google.com/open?id=1jlYA1BqRk4lWZJi1vTA0CXyZU3r_Ubo3

**Comment by liquidcitymotors** [comment]
@SteveRussell33 Thanks for tracking that down. I will fix on the next commit. @caecos I am sorry that I have not been able to properly test a windows build; I have been very busy with other aspects of this project. I will find a windows machine and try to build after work tonight.

**Comment by caecos** [comment]
Many thanks and do not apologized... you offers your works free and that all we can wait for...regards...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Will Mitchell <notifications@github.com>
Envoyé : lundi, janvier 14, 2019 14:51
À : liquidcitymotors/Via-for-VCVRack
Cc : caecos; Mention
Objet : Re: [liquidcitymotors/Via-for-VCVRack] Will not compile on Windows 10 (#12)


@SteveRussell33<https://github.com/SteveRussell33> Thanks for tracking that down. I will fix on the next commit. @caecos<https://github.com/caecos> I am sorry that I have not been able to properly test a windows build; I have been very busy with other aspects of this project. I will find a windows machine and try to build after work tonight.

**Comment by caecos** [comment]
Unable to download the Dropbox files...

**Comment by caecos** [comment]
Unable to download the file... error file does not exist...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : SteveRussell33 <notifications@github.com>
Envoyé : lundi, janvier 14, 2019 12:42
À : liquidcitymotors/Via-for-VCVRack
Cc : caecos; Mention
Objet : Re: [liquidcitymotors/Via-for-VCVRack] Will not compile on Windows 10 (#12)


Starling_Via-0.9.0-win.zip

https://drive.google.com/open?id=1jlYA1BqRk4lWZJi1vTA0CXyZU3r_Ubo3

**Comment by SteveRussell33** [comment]
Sorry, thought you grabbed the file after I uploaded it to my GoogleDrive - which I then cleared out of some old files.
Reuploaded: https://drive.google.com/open?id=1s-vX2sj-b3jNjj5r5JBHpYMMJiNHxEdn

**Comment by caecos** [comment]
Compile like a cool breeze...thanks and bravo for the improvements...regards

**Comment by SteveRussell33** [comment]
@liquidcitymotors No problem my friend, happy to help! Love the panel artwork btw! Very nice.

**Comment by caecos** [comment]
I have downloaded the and it works well... quite similar to my compilation now... with your help... indeed...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : SteveRussell33 <notifications@github.com>
Envoyé : mardi, janvier 15, 2019 13:20
À : liquidcitymotors/Via-for-VCVRack
Cc : caecos; Comment
Objet : Re: [liquidcitymotors/Via-for-VCVRack] Will not compile on Windows 10 (#12)


Sorry, thought you grabbed the file after I uploaded it to my GoogleDrive - which I then cleared out of some old files.
Reuploaded: https://drive.google.com/open?id=1s-vX2sj-b3jNjj5r5JBHpYMMJiNHxEdn
