### ISSUE TITLE
0.6 API updates

### ISSUE THREAD

**Issue by phdsg** [liquidcitymotors/Via-for-VCVRack#2]
rack v0.6 is coming soon and there are a few changes necessary to make plugins work with the new rack API. (https://github.com/VCVRack/Rack/issues/258#issuecomment-346222777)
in case you need help with the transition, the repair team is here: https://github.com/VCVRack/community/issues/269.

**Comment by liquidcitymotors** [comment]
@phdsg the most recent commit to the master branch should be compatible with the 0.6 API

**Comment by phdsg** [comment]
thx, gonna test later today...

**Comment by liquidcitymotors** [comment]
Hi! I am going to close this as there is a thread going about 0.6 API compatibility in #5. Thanks again for checking in!
