### ISSUE TITLE
GATESEQ patterns outputing wrong sequences

### ISSUE THREAD

**Issue by anaday** [liquidcitymotors/Via-for-VCVRack#27]
PTN 1 one plays the pattern indicated in the tooltip. eg I set it to play 4 beats per 16. I get a pattern of 4 beats per 16 as expected.
Setting PTN 2 does nothing. It plays the same pattern as PTN 2 no matter what the knob is set to. Set it to 1 beat per 16. It plays the 4 beats set in PTN 1. Play an odd number beat (eg 5) in PTN 1. PTN 2 plays the same pattern offset by 1.

Video of issue:
https://drive.google.com/file/d/1CDSAvI61DKpVkoxiEjrwgO2hpytx3cgw/view?usp=sharing

Tried to save the patch. It saved, but when I tried to reopen it, Rack hung and I had to kill it. Closing Rack with the patch running and then reopening Rack, the patch hangs and you have to kill Rack. Sorry, nothing in the log. 

Hope this helps. Thanks.

Edit: On Mac High Sierra 10.13.6

**Comment by liquidcitymotors** [comment]
Thanks for the info! This should be fixed in the latest commit. 

Some of the changes were in the Via submodule, so just be sure to update that as well. 

If you run into any further issues, just reopen the issue and I'll be happy to help.

**Comment by SteveRussell33** [comment]
Comment https://github.com/starlingcode/Via-for-Rack/commit/29e8efc73ef9ea421c80018554ec9caff8d07c2b#r58410409

**Comment by liquidcitymotors** [comment]
Oof, I need to step a bit more carefully here, there are some major problems with the last commit. Working on cleaning things up now.

**Comment by liquidcitymotors** [comment]
OK things seem to be working with the latest commit :sweat_smile:
