### ISSUE TITLE
win, for 0.5.1, as is

### ISSUE THREAD

**Issue by dizzisound** [liquidcitymotors/Via-for-VCVRack#3]
[VCVia-0.5.0-win.zip](https://github.com/liquidcitymotors/VCVia/files/1786105/VCVia-0.5.0-win.zip)

**Comment by liquidcitymotors** [comment]
I'm going to close this, but I welcome you to take a look at my response in #7 about whether or not I should be maintaining an updated 0.5-compatible version

**Comment by dizzisound** [comment]
Hi, IMO good to go closing this, maybe 0.5 will stay for some time or some users, but the released or archived binaries could well serve this. And Rack 0.6.* could evolve quickly, if I'd be a plugin developer I'd better spend on it :-) 
Best
