### ISSUE TITLE
v2: Build failure

### ISSUE THREAD

**Issue by cschol** [liquidcitymotors/Via-for-VCVRack#36]
The version submitted to the Rack library fails to build:

```
./Via/modules/inc/osc3.hpp:766:5: note: during field initialization in this constructor                                                                    
    ViaOsc3(std::string binPath) : osc3UI(*this) {                                                                                                         
    ^                                                                      
In file included from src/scanner.cpp:2:
In file included from src/via-module.hpp:4:                                                                                                                
src/via-params.hpp:3:10: fatal error: 'starling-rack-ui.hpp' file not found                                                                                
#include "starling-rack-ui.hpp"      
         ^~~~~~~~~~~~~~~~~~~~~~                                                                                                                            
1 error generated.                         
```

**Comment by liquidcitymotors** [comment]
Thanks @cschol! ***bart simpson writing on the chalkboard: "i will always do a clean build of library submissions before submitting"*** 

Can you try commit e1637cdd8c2fce8f3a41ca59db2e9239ca1f5ab4? That one built fine on my Mac once all submodules were fully updated.

**Comment by SteveRussell33** [comment]
Just to add: https://github.com/starlingcode/Via-for-Rack/commit/e1637cdd8c2fce8f3a41ca59db2e9239ca1f5ab4 builds successfully on Win

**Comment by cschol** [comment]
Still doesn't work, but I figured out why. Your dependency submodules are cloned into `dep` directory. The build process will execute `make cleandep` (defined in `dep.mk`) and will delete that directory in the beginning of the build process. You should move your submodules to `src/dep`.

**Comment by liquidcitymotors** [comment]
Well that makes things easy for me, thanks so much for figuring this out @cschol and thanks for the sanity check @SteveRussell33! 

I moved the submodules as suggested and updated the Makefile. A clean make seemed to work fine on my mac, how is 7ceab8f69b5e95c41d0859b64857686fc96915fc looking?

**Comment by liquidcitymotors** [comment]
I think this will good because the issue has been well defined, going to close this and move back over to the library issue tracker.

**Comment by cschol** [comment]
All good now. Thank you!
