### ISSUE TITLE
RACK_DIR is missing from Makefile

### ISSUE THREAD

**Issue by cschol** [liquidcitymotors/Via-for-VCVRack#5]
The `Makefile`  should define a variable called `RACK_DIR`, which can be set to the location of the Rack source code. This allows compiling the plugin outside of the Rack source tree.

See [API Update Thread](https://github.com/VCVRack/Rack/issues/258#issuecomment-365346155).

**Comment by liquidcitymotors** [comment]
Hi! Thanks for catching this. I added it following the example of the template in the most recent commit.

**Comment by phdsg** [comment]
you also might wanna change the slug. unless "CompanyName_Via" is the real thing :)

**Comment by liquidcitymotors** [comment]
This is actually a software model of a soon to be released physical module designed by @smrl and myself. Naming the company has proved harder than designing the module.

**Comment by cschol** [comment]
Just be sure to get the company resolved before plugin use ramps up. Changing the slug later is a **pain** for users. We can help you with a name. ;)

**Comment by liquidcitymotors** [comment]
joking aside, coming up with a name is a huge priority for us. once we do that and finalize the available wavetables, the plugin should be ready for release into the community repository and plugin manager subject to testing across operating systems.

**Comment by cschol** [comment]
One more issue here: `RACK_DIR` needs to be **used** to find the Rack specific components, e.g. `plugin.mk`. Right now, the Makefile still uses `../../plugin.mk`.

**Comment by liquidcitymotors** [comment]
Hey @cschol, I did another pass at the VCVRack version of Via and we are getting much closer. This update you suggest should be among the changes in my last few commits. Could you check that the latest commit in master has sorted out this issue? Thanks to you and the rest of the community for your help with getting novice developers such as myself up to speed.

**Comment by cschol** [comment]
Thank you. The latest version looks good. The only thing that is missing is the "Company Name" (unless that's the actual name :)).

**Comment by cschol** [comment]
@liquidcitymotors See the community [README](https://github.com/VCVRack/community/blob/master/README.md#for-plugin-developers) for instructions on how to get the plugin added to the community repository.

**Comment by liquidcitymotors** [comment]
Thanks! I will be be adding this to the repository in the (hopefully very) near future.
