### ISSUE TITLE
graphics problem

### ISSUE THREAD

**Issue by davephillips** [liquidcitymotors/Via-for-VCVRack#6]
Fedora 23 Linux
Rack master (0.6.x dev)

Greetings ! The attached screenshot tells the story. Is this what I should be seeing ? I launch Rack from the command prompt, all components appear to be loading correctly. Please advise if I'm not getting something right. Btw, I build your plugin from source (master branch).

![viaforrack](https://user-images.githubusercontent.com/7815938/37663539-cace3f5a-2c2f-11e8-8fd2-ec906024b746.png)

**Comment by liquidcitymotors** [comment]
Thanks so much for bringing this to our attention. It would appear that "/res/Davies1900hvia.svg" is not loading properly. If you do not get any error messages about missing SVG files when launching Rack from source, it looks like I need to do some more research on the knob object and compatibility with different SVG files. We will let you know when this is resolved, hugely helpful.

**Comment by liquidcitymotors** [comment]
Ok I removed a gradient from the SVG in the latest commit which seems like a decent place to start because I believe gradients are not supported in components. That might explain why it renders to gray on some operating systems (like mine and another test linux build), but not yours.

**Comment by liquidcitymotors** [comment]
@davephillips missed a few steps here; this had nothing to do with your system and everything to do with me not properly updating rack. could you test? this should have been fixed on the latest commit

**Comment by davephillips** [comment]
Hey, thanks for the message. I pulled the latest git sources, rebuilt your module and everything looks okay now. Good work ! :)

**Comment by liquidcitymotors** [comment]
Thanks a lot @davephillips!
