### ISSUE TITLE
050 mac 

### ISSUE THREAD

**Issue by cfoulc** [liquidcitymotors/Via-for-VCVRack#7]
[VCVia-0.5.0-mac.zip](https://github.com/liquidcitymotors/Via-for-VCVRack/files/1838688/VCVia-0.5.0-mac.zip)

**Comment by liquidcitymotors** [comment]
Thanks @cfoulc ! Fair warning, the 0.5 branch lags significantly behind master (which is the 0.6 compatible version). Would it benefit you and others if I updated the 0.5 branch to a current version? Or do you think most users have migrated to Rack 0.6? If its good practice to keep the 0.5 branch current with the latest stable release, I can do that.

**Comment by cfoulc** [comment]
i do think most users have migrated, i'm neither maintaining 0.5.0 version of my modules, that was a post from 17 days ago :)

**Comment by liquidcitymotors** [comment]
ok perfect thats good insight. time flies! I will be quicker on the issue tracker going forward FYI. thanks!
